export enum TEST_ITEM_TYPES {
    SUITE = 'SUITE',
    TEST = 'TEST',
    STEP = 'STEP',
    BEFORE_SUITE = 'BEFORE_SUITE',
    BEFORE_TEST = 'BEFORE_TEST',
    AFTER_SUITE = 'AFTER_SUITE',
    AFTER_TEST = 'AFTER_TEST',
}
